import json

TOKEN = 'Discord bot token'
CARDS_FILE_PATH = "./cards.json"
with open(CARDS_FILE_PATH) as cards_file:
    ALL_CARDS = json.loads(cards_file.read())

GENDER_KEY = "GENDER"
AGE_KEY = "AGE"
ORIENTATION_KEY = "ORIENTATION"
PHOBIES_KEY = "PHOBIES"
PERSONALITIES_KEY = "PERSONALITIES"
HOBBIES_KEY = "HOBBIES"
SKILLS_KEY = "SKILLS"
HEALTH_KEY = "HEALTH"
INVENTORY_KEY = "INVENTORY"
PROFESSION_KEY = "PROFESSION"

PLAYER_PROFILE_KEYS = [
    GENDER_KEY,
    AGE_KEY,
    ORIENTATION_KEY,
    PHOBIES_KEY,
    PERSONALITIES_KEY,
    HOBBIES_KEY,
    SKILLS_KEY,
    HEALTH_KEY,
    INVENTORY_KEY,
    PROFESSION_KEY
]
ACTIONCARDS_KEY = "ACTIONCARDS"
CATASTROPHE_KEY = "CATASTROPHE"

BUNKER_PROFILE_KEYS = [

]
